# Created with Komac v1.9.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Cloudflare.cloudflared
PackageVersion: 2023.7.1
InstallerLocale: en-US
InstallerType: msi
AppsAndFeaturesEntries:
- UpgradeCode: '{23f90fdd-9328-47ea-ab52-5380855a4b12}'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/cloudflare/cloudflared/releases/tag/2023.7.1
  InstallerSha256: 24B584C38F60D03D252E9759972F4B045954E8EA47A0D27A7CC14D958060DCDA
  ProductCode: '{43D0F72C-53BE-423A-B583-F60639E405FB}'
- Architecture: x64
  InstallerUrl: https://github.com/cloudflare/cloudflared/releases/tag/2023.7.1
  InstallerSha256: 24B584C38F60D03D252E9759972F4B045954E8EA47A0D27A7CC14D958060DCDA
  ProductCode: '{AA096A54-9F8A-4B50-A539-E3D67C73BD23}'
ManifestType: installer
ManifestVersion: 1.4.0
