# Created with Komac v1.9.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Cloudflare.cloudflared
PackageVersion: 2023.7.1
InstallerLocale: en-US
InstallerType: msi
AppsAndFeaturesEntries:
- UpgradeCode: '{23f90fdd-9328-47ea-ab52-5380855a4b12}'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/cloudflare/cloudflared/releases/tag/2023.7.1
  InstallerSha256: 24B584C38F60D03D252E9759972F4B045954E8EA47A0D27A7CC14D958060DCDA
  ProductCode: '{931D3DBC-FBD2-4F46-B9B5-DCD65314E73B}'
- Architecture: x64
  InstallerUrl: https://github.com/cloudflare/cloudflared/releases/tag/2023.7.1
  InstallerSha256: 24B584C38F60D03D252E9759972F4B045954E8EA47A0D27A7CC14D958060DCDA
  ProductCode: '{773B937A-F134-42EB-8F5E-B9E5406D47EB}'
ManifestType: installer
ManifestVersion: 1.4.0
